config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events, only: [:new, :create]
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :feedbacks, only: [:new, :create]

  root 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/gallery', to: 'pages#gallery'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
enum status: { draft: 0, published: 1 }
belongs_to :user
validates_presence_of :title, :description, :user_id
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:toggle_status]}, site_admin: :all
  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.all
    else
      @blogs = Blog.published
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end

    def require_same_user
      if (!logged_in?(:site_admin) && (current_user != @blog.user))
       flash[:danger] = "You can only make changes to your own articles"
     redirect_to root_path
  end

end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <% blog.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
  <%= message %>
</div>
<% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :blog_title ,class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, id: :blog_description ,class: 'form-control', placeholder: 'Description', rows: 10 %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
	<h1>Edit blog</h1>
	<%= render 'form', blog: @blog %>

	<%= link_to 'Show', @blog %> |
	<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="container">
  <div style="padding-top: 15px;">
  <%= link_to 'New Blog', new_blog_path, class: 'btn btn-primary' %>
  </div>
      <div class="blog-header">
        <div class="container">
            <h1 class="text-center">ACM Blog</h1>
          <p class="lead blog-description text-center">Information about all latest events.</p>
        </div>
      </div>
    </header>

  <% @blogs.each do |blog| %>

  <div class="blog-post">

    <div class="blog-post-title">
      <%= blog.title  %>
    </div>

    <div class="blog-post-meta">
    <%= blog.description %>
    <br>
  </div>
  <div>
    <% if logged_in?(:site_admin) %>
    <%= link_to blog.status, toggle_status_blog_path(blog) %>
    <% end %>
    </div>


<% if logged_in?(:site_admin) || (current_user && blog.user_id == current_user.id) %>
  <%= link_to fa_icon("edit 2x"), edit_blog_path(blog), class: "color-black" %> |
    <%= link_to fa_icon("trash 2x") , blog_path(blog), method: :delete,data: {confirm: "Are you sure?"} ,class: "color-red" %> |
<% end %>

<%= link_to fa_icon("chevron-right 2x"), blog_path(blog) %>

  </div>
  <% end %>
<hr>
</div>

app/views/blogs/new.html.erb
<br>
<div class="container">	
	<h1 class="text-center">New Blog</h1>
	<br>
	<%= render 'form', blog: @blog %>

	<%= link_to 'Back', blogs_path %>
	<hr>
</div>

app/views/blogs/show.html.erb
<br>
<div class="container">

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
	<small>Created By: <%= User.find(@blog.user_id).email %></small>
</p>

<% if logged_in?(:site_admin) || current_user && @blog.user_id == current_user.id %>
	<%= link_to fa_icon("edit 2x"), edit_blog_path(@blog), class: "color-black" %> |
    <%= link_to fa_icon("trash 2x") , blog_path(@blog), method: :delete,data: {confirm: "Are you sure?"} ,class: "color-red" %> |
<% end %>

<%= link_to fa_icon("chevron-circle-left 2x"), blogs_path %>

</div>
<hr>