config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :events, only: [:new, :create]
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  resources :feedbacks, only: [:new, :create]

  root 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/gallery', to: 'pages#gallery'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_app_footer.html.erb
    <footer class="blog-footer">
      <p>Association for Computing Machinery<small>(ACM)</small><a href="https://acm.org/"> ACM OFFICIAL WEBSITE</a> by 
      	<a href="https://ncuindia.edu">NCU</a>.
      </p>
		<p>
          <%= link_to( (fa_icon "facebook 2x", class: "left-pad white-link"), "https://www.facebook.com/acmncu" ) %>
          <%= link_to( (fa_icon "instagram 2x", class: "left-pad white-link"), "https://www.instagram.com/acmncu" ) %>
          <%= link_to( (fa_icon "twitter 2x", class: "left-pad white-link"), "www.facebook.com" ) %>
		</p>

      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

app/views/shared/_app_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= image_tag("logo.png", width: '5%') %>
  <a class="navbar-brand" href="#"> ACM </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li> <%= link_to "Home", root_path, class: 'nav-link active' %></li>

      <li> <%= link_to "About Us", about_path, class: 'nav-link  active' %></li>

      <li> <%= link_to "Gallery", gallery_path, class: 'nav-link active' %></li>

      <li> <%= link_to "Register an Event", new_event_path, class: 'nav-link active' %></li>

      <li> <%= link_to "Feedback", new_feedback_path, class: 'nav-link active' %></li>

      <li> <%= link_to "Blog", blogs_path, class: 'nav-link active' %></li>

    <% if current_user %>
      <li> <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link active temp_class' %> </li>

    <% else %>
      <li>        <%= link_to "Log in", new_user_session_path, class: 'nav-link active temp_class' %>      </li>
      <li>        <%= link_to "Sign up", new_user_registration_path, class: 'nav-link active' %>     </li>
    <% end %>

    </ul>
  </div>
</nav>